import raw from './licenses.json';

/**
 * The open-source credits shown in More > Legal > Open-source licenses.
 * licenses.json is generated by `node scripts/gen-licenses.mjs` (never edited by
 * hand): npm packages from package-lock.json, the native libraries the Android
 * and iOS builds confirm, and the fonts. Each license text is stored once;
 * entries point to it by index.
 */

export type LicenseKind = 'font' | 'native' | 'npm';
export type LicensePlatform = 'android' | 'ios';

export type LicenseEntry = {
  name: string;
  /** Missing for umbrella entries (AndroidX) or when the build gives no version. */
  version?: string;
  /** SPDX id or expression ("MIT", "Apache-2.0 OR BSL-1.0 OR MIT"). */
  license: string;
  kind: LicenseKind;
  /** Who makes it (fonts and native libraries only). */
  by?: string;
  /** Which apps carry it (native libraries only). */
  platforms?: LicensePlatform[];
  /** Copyright lines, or a note, shown above the license text. */
  notice?: string;
  /** Indices into `texts`, in display order (LICENSE before NOTICE). */
  texts: number[];
};

export type LicenseData = {
  note: string;
  counts: { fonts: number; native: number; npm: number };
  packages: LicenseEntry[];
  texts: string[];
};

export const licenseData = raw as LicenseData;

export const LICENSES_COPY = {
  title: 'Open-source licenses',
  intro: 'Tekmadev Admin is built with these open-source projects. Thank you.',
  native: 'Native libraries and fonts',
  npm: 'JavaScript packages',
} as const;

export type LicenseRow =
  | { type: 'header'; key: string; title: string; count: number }
  | { type: 'item'; key: string; entry: LicenseEntry };

/** The list: native libraries and fonts first (what ships inside the app binary), then the npm packages. */
export function licenseRows(packages: readonly LicenseEntry[] = licenseData.packages): LicenseRow[] {
  const native = packages.filter((p) => p.kind !== 'npm');
  const npm = packages.filter((p) => p.kind === 'npm');
  const rows: LicenseRow[] = [];
  const section = (key: string, title: string, entries: LicenseEntry[]) => {
    if (!entries.length) return;
    rows.push({ type: 'header', key: `header:${key}`, title, count: entries.length });
    for (const entry of entries) rows.push({ type: 'item', key: entryKey(entry), entry });
  };
  section('native', LICENSES_COPY.native, native);
  section('npm', LICENSES_COPY.npm, npm);
  return rows;
}

export function entryKey(entry: LicenseEntry): string {
  return `${entry.kind}:${entry.name}@${entry.version ?? ''}`;
}

/** "Android", "iOS" or "Android and iOS". */
export function platformLabel(platforms: readonly LicensePlatform[] | undefined): string | null {
  if (!platforms?.length) return null;
  const names = platforms.map((p) => (p === 'ios' ? 'iOS' : 'Android'));
  return names.length === 2 ? `${names[0]} and ${names[1]}` : names[0];
}

/** The line under a name: "4.9.2 · Apache-2.0 · Android". */
export function entrySubtitle(entry: LicenseEntry): string {
  const kind = entry.kind === 'font' ? 'Font' : platformLabel(entry.platforms);
  return [entry.version, entry.license, kind].filter(Boolean).join(' · ');
}

/** What TalkBack and VoiceOver read for a row: "OkHttp, version 4.9.2, Apache-2.0, Android". */
export function entryA11yLabel(entry: LicenseEntry): string {
  const kind = entry.kind === 'font' ? 'Font' : platformLabel(entry.platforms);
  return [entry.name, entry.version ? `version ${entry.version}` : null, entry.license, kind].filter(Boolean).join(', ');
}

/** The license texts of an entry, in order. */
export function entryTexts(entry: LicenseEntry, texts: readonly string[] = licenseData.texts): string[] {
  return entry.texts.map((index) => texts[index]).filter((text): text is string => typeof text === 'string');
}
